language: node_js
node_js:
  - node
install:
  - npm i
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  edge: true
  token:
    secure: j349G8W1Q89kcbFiZsQ+3GRSrBEIZCWQD1GMa9poZyZA3xWzrlxnxC4IgPEdVCWAatYk20RVomG7ijQZggPFZ15Ks4Pk2cxEKjWYyOoj/khI3hVDENCtp4UGTmg6nrUWny10L8gUajoW9MrIz1Hbt43RzJUIxf11mT5KDY4x8WMLPedoNChSIC+YE1keifSenMw1YV/KKcW9hsrnpkw6rzmARZxdQrY31KJttnDHGtJdMqQu0Ei4z2lvO+4kh0fcxBcNu4DNegUzJ8EBu1jZlc+IDvL3BfWTDkcZd4CiEJX3mr7KYVIPY7Zl/NNsGKVMvBqvILJWiyY6PjL7r/q67mGGf3Jr/4Mgv+IjDqf5JJczX+FnGXuV7/RMgijitoXbHvEtxBu6a9rRUsMM1AZsm57yz+BDcKPZYZ/xarXq0hNQouWh8XCMgEchUUB18e3jPlRH90QV9Ik2sA6VqIYFGepE3T2/fihUuwsYJiKnfPKY1RQaX8Z07KnHaVzg5ksnmP1wQnVaZ4DjzPST7LON85K237Os/DCGFTbXpiA4Ufm3i842R3rHLFAlNIPL08yqKcPS28Ee5fg7CFjMe0yJc7XXvYwFpSu0p9F4/UgybnFqy2LBcvMkkVvHj9O2FQq7d2H2DuxxNjszqrcIKXdHkJL51tSVeYSl98Vo00nQpNs=
